onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  react-router@>=7.0 <=7.5.1: '>=7.5.2'
  react-router@>=7.2.0 <=7.5.1: '>=7.5.2'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.3.0 <=6.3.3: '>=6.3.4'
