onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  ajv@<8.18.0: '>=8.18.0'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
  react-router@>=7.0.0 <7.9.6: '>=7.9.6'
  react-router@>=7.0.0 <=7.11.0: '>=7.12.0'
